server {
  listen 80;
  server_name _;
  root /media;

  add_header Access-Control-Allow-Origin "*" always;
  add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
  add_header Access-Control-Allow-Headers "*" always;

  if ($request_method = OPTIONS) {
    return 204;
  }

  location / {
    autoindex on;
    try_files $uri =404;
  }
}
